language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install

script:
  - cd module/Phph/Site/test
  - phpunit --coverage-text

matrix:
  allow_failures:
     - php: hhvm
